# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push,pull_request] # 추후에 push는 빼줘야함.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test: # Job id
    runs-on: ubuntu-latest # Runner
    steps:
    - uses: actions/checkout@v3 # Step
    - name: Set up JDK 11 
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - name: Cache gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
